//
// Warning:
// This file is generated by go compiler, don't change it!!!
// Generated Time: "2022-01-12 13:37:38"
//
package typex

type Version struct {
	Version   string
	ReleaseTime string
}

var DefaultVersion = Version{
	Version:   `V0.0.2-dd4cfd8145bb3e4`,
	ReleaseTime: "2022-01-12 13:37:38",
}

